make: update protos local (#154)
Add makefile option to update protos from local clone.

diff --git a/crates/sui-rpc/Makefile b/crates/sui-rpc/Makefile
--- a/crates/sui-rpc/Makefile
+++ b/crates/sui-rpc/Makefile
@@ -15,6 +15,7 @@ test:
 	cargo nextest run --all-features
 	cargo test --doc
 
+# Update vendored protos from sui-apis master branch.
 .PHONY: update-protos
 update-protos:
 	@rm -rf vendored/sui-apis
@@ -22,6 +23,23 @@ update-protos:
 	@git clone -q --depth=1 https://github.com/MystenLabs/sui-apis.git vendored/sui-apis
 	@mv vendored/sui-apis/proto vendored/
 	@rm -rf vendored/sui-apis
+
+# Update vendored protos from a local clone of sui-apis.
+# Example invocation:
+#     make -C crates/sui-rpc update-protos-local /path/to/sui-apis
+.PHONY: update-protos-local
+update-protos-local:
+	@if [ -z "$(filter-out $@,$(MAKECMDGOALS))" ]; then \
+		echo "Error: Path not provided. Usage: make update-protos-local /path/to/sui-apis"; \
+		exit 1; \
+	fi
+	@if [ ! -d "$(filter-out $@,$(MAKECMDGOALS))/proto" ]; then \
+		echo "Error: $(filter-out $@,$(MAKECMDGOALS))/proto does not exist"; \
+		exit 1; \
+	fi
+	@rm -rf vendored/proto
+	@cp -r "$(filter-out $@,$(MAKECMDGOALS))/proto" vendored/
+	@echo "Updated protos from $(filter-out $@,$(MAKECMDGOALS))"
 
 .PHONY: diff-protos
 diff-protos:
